config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "callbacks" }

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end
  
  root 'destinations#index'

  resources :destinations do
    resources :attractions, only: [:new, :create, :show, :edit, :update, :destroy]
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attraction.rb
class Attraction < ApplicationRecord
    belongs_to :destination

    validates :name, presence: true, uniqueness: true

    scope :recommended, -> { where(recommend: true).order('name asc') }
    scope :not_recommended, -> { where(recommend: false).order('name asc') } 

end

app/models/country.rb
class Country < ApplicationRecord
    has_many :destinations
    has_many :users, through: :destinations

    validates :name, presence: true, uniqueness: true
    
end

app/models/destination.rb
class Destination < ApplicationRecord
    belongs_to :user, inverse_of: :destinations
    belongs_to :country
    has_many :attractions

    accepts_nested_attributes_for :country

    validates :name, presence: true

    scope :visited, -> { where(visited: true).order('name asc') }
    scope :not_visited, -> { where(visited: false).order('name asc') }

    def country_attributes=(att)
        if !att[:name].blank? && att[:id].blank?
            self.country = Country.find_or_create_by(name: att[:name])
        elsif !att[:id].blank?
            self.country = Country.find_by(id: att[:id])
        end
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :destinations
  has_many :countries, through: :destinations

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.name = auth.info.name
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

#:trackable,

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base  
end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
    before_action :authenticate_user!, :set_destination

    def new
        @attraction = @destination.attractions.build
    end

    def create
        @attraction = @destination.attractions.build(attraction_params)
        if @attraction.save
            redirect_to destination_path(@destination)
        else
            render :new
        end
    end

    def show
        set_attraction
    end

    def edit
        set_attraction
    end

    def update
        set_attraction
        if @attraction.update(attraction_params)
            redirect_to destination_path(@destination)
        else
            render :edit
        end
    end

    def destroy
        set_attraction
        @attraction.delete
        redirect_to destination_path(@destination)
    end

    private

    def set_destination
        @destination = current_user.destinations.find_by(id: params[:destination_id])
    end

    def set_attraction
        @attraction = @destination.attractions.find_by(id: params[:id])
    end

    def attraction_params
        params.require(:attraction).permit(
            :name,
            :url,
            :kind_of_attraction,
            :recommend,
            :comments
        )
    end
end

app/controllers/callbacks_controller.rb
require 'pry'
class CallbacksController < Devise::OmniauthCallbacksController
    def github
        @user = User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect @user
    end
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
    before_action :authenticate_user!, :set_user

    def index
        if params.has_key?(:destination) && !params[:destination][:country_id].empty?
            search = params[:destination][:country_id]
            @destinations = @user.destinations.where(country_id: search)
        else
            @destinations = @user.destinations
        end
    end

    def new
        @destination = @user.destinations.build
        @destination.build_country
    end

    def create
        @destination = @user.destinations.new(destination_params)

        if @destination.save
            redirect_to root_path
        else
            render :new
        end
    end

    def show
        set_destination
    end

    def edit
        set_destination
    end

    def update
        set_destination
        dp = destination_params
        dp[:country_attributes][:id] = ""
        if @destination.update(dp)
            redirect_to destination_path(@destination)
        else
            render :edit
        end
    end

    def destroy
        set_destination
        @destination.delete
        redirect_to root_path
    end

    private

    def set_user
        @user = current_user
    end

    def set_destination
        @destination = @user.destinations.find_by(id: params[:id])
    end

    def destination_params
        params.require(:destination).permit(
            :name,
            :visited,
            :year_of_visit,
            :recommend,
            :revisit,
            :notes,
            :country_id,
            country_attributes: [
                :name,
                :id
            ]
        )
    end
end

app/controllers/dos_and_donts_controller.rb
class DosAndDontsController < ApplicationController
    before_action :authenticate_user!
    
    def index
    end

    def new
    end

    def create
    end

    def show
    end

    def edit
    end

    def update
    end

    def destroy
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params
        params.require(:user). permit( :name,
                                       :email,
                                       :password,
                                       :password_confirmation)
    end

    def account_update_params
        params.require(:user). permit( :name,
                                       :email,
                                       :password,
                                       :password_confirmation,
                                       :current_password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/attractions/_form.html.erb
<% if attraction.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(attraction.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>
 
    <ul>
    <% attraction.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [destination, attraction] do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %> <br>

    <%= f.label :kind_of_attraction, 'Kind of Attraction'%>
    <%= f.text_field :kind_of_attraction %> <br>

    <%= f.label :recommend %>
    <%= f.check_box :recommend %> <br>

    <%= f.label :url, 'Website' %>
    <%= f.text_field :url %> <br>

    <%= f.label :comments, 'Comments: ' %> <br>
    <%= f.text_area :comments %> <br>

    <%= f.submit 'Add Attraction' %>
<% end %>

app/views/attractions/edit.html.erb
<h2>Add a New Attraction</h2> <br>

<%= render partial: 'form', locals: {destination: @destination, attraction: @attraction, button_text: 'Update Attraction'} %>

app/views/attractions/new.html.erb
<h2>Add a New Attraction</h2> <br>

<%= render partial: 'form', locals: {destination: @destination, attraction: @attraction, button_text: 'Add Attraction'} %>

app/views/attractions/show.html.erb
<h2>Attraction: <%= @attraction.name %></h2>

<div>
    <strong>Visited during trip to <%= @destination.name %>, <%= @destination.country.name %></strong> <br>

    Kind of attraction: <%= @attraction.kind_of_attraction %> <br>

    Would recommend to others? - <%=  @attraction.recommend? ? "Yes" : "No" %> <br>

    Website: <%= @attraction.url %> <br>

    Comments: <%= @attraction.comments %> <br>
</div> <br>

<%= link_to 'Edit Attraction', edit_destination_attraction_path(@destination, @attraction) %> <br>
<%= link_to 'Delete Attraction', destination_attraction_path(@destination, @attraction), method: :delete %>

app/views/destinations/_form.html.erb
<% if destination.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(destination.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>
 
    <ul>
    <% destination.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for destination do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %> <br>

    Select Country<%= f.collection_select :country_id, Country.all, :id, :name, include_blank: true %> <br>

    <%= f.fields_for :country, destination.country do |c| %>
      <%= c.label :name, 'OR Add a New Country' %>
      <%= c.text_field :name %> <br>
    <% end %>
        
    <%= f.label :visited, 'Visited?' %>
    <%= f.check_box :visited? %> <br>

    <%= f.label :year_of_visit %>
    <%= f.number_field :year_of_visit %> <br>

    <%= f.label :recommend, 'Would you recommend this destination to others?' %>
    <%= f.check_box :recommend? %> <br>

    <%= f.label :revisit, 'Would you like to revisit this destination?' %>
    <%= f.check_box :revisit? %> <br>

    <%= f.label :notes, 'Notes:' %>  <br>
    <%= f.text_area :notes %> <br>

    <%= f.submit button_text %>
<% end %>

app/views/destinations/edit.html.erb
<h2>Edit Destination</h2> <br>

<%= render partial: 'form', locals: {user: @user, destination: @destination, button_text: 'Update Information'} %>

app/views/destinations/index.html.erb
<h2>Welcome, <%= @user.name %>!</h2>

<strong>To see only destinations from a given country: </strong>

<%= form_tag(destinations_path, method: :get) do %>
    <%= collection_select :destination, :country_id, Country.all, :id, :name, include_blank: true %>
    <%= submit_tag 'Search' %>
<% end %> <br>

<% if !@destinations.visited.empty? %>
    <div>
        <h3>Places I Have Visited</h3>

        <% @destinations.visited.each do |d| %>
            <%= link_to d.name, destination_path(d) %>, <%= d.country.name %> <br>
        <% end %> <br>
    <div>
<% end %>

<% if !@destinations.not_visited.empty? %>
    <div>
        <h3>Places I Want To Visit</h3>

        <% @destinations.not_visited.each do |d| %>
            <%= link_to d.name, destination_path(d) %>, <%= d.country.name %> <br>
        <% end %> <br>
    <div>
<% end %>

<%= link_to 'Add Destination', new_destination_path %> <br>

app/views/destinations/new.html.erb
<h2>Add a New Destination</h2> <br>

<%= render partial: 'form', locals: {user: @user, destination: @destination, button_text: 'Add Destination'} %>

app/views/destinations/show.html.erb
<div>
    <h2>Destination: <%= @destination.name %>, <%= @destination.country.name %></h2> <br>

    <% if @destination.visited? %> 
        <strong> Year of last visit <%= @destination.year_of_visit %> </strong> <br>

        Would recommend to others? - 
        <%=  @destination.recommend? ? "Yes" : "No" %> <br>

        Book a return visit? - 
        <%=  @destination.revisit? ? "Yes" : "No" %> <br>
    <% else %>
        <strong> Not yet visited </strong> <br>

        <% if @destination.year_of_visit %>
            <strong> Year of future visit: <%= @destination.year_of_visit %> </strong> <br>
        <% end %>
    <% end %><br>
    
    Notes: <%=  @destination.notes%> <br>

    <%= link_to "Edit Destination", edit_destination_path(@destination) %> <br>
    <%= link_to "Delete Destination", destination_path(@destination), :method => :delete %> <br>
</div> <br>


<div>
    <h3>Attractions of <%= @destination.name %></h3>

    <% if !@destination.attractions.recommended.empty? %>
        <h4>Recommended</h4>

        <% @destination.attractions.recommended.each do |attraction| %>
            <%= link_to attraction.name, destination_attraction_path(@destination, attraction) %> <br>
        <% end %>
    <% end %>

    <% if !@destination.attractions.not_recommended.empty? %>
        <h4>Not recommended</h4>

        <% @destination.attractions.not_recommended.each do |attraction| %>
            <%= link_to attraction.name, destination_attraction_path(@destination, attraction) %> <br>
        <% end %>
    <% end %> <br>

    <%= link_to 'Add Attraction', new_destination_attraction_path(@destination) %>
</div>

app/views/layouts/_navbar.html.erb
<nav>
    <ul>
        <% if !user_signed_in? %>
            <li><%= link_to 'Signup', new_user_registration_path %></li>
            <li><%= link_to 'Login', login_path %></li>
        <% else %>
            <li><%= link_to "#{current_user.name}'s Homepage", destinations_path %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: 'delete' %></li>
        <% end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsProjectTravelLog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <h1>Travel Log Project</h1>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>